---

- name: Download Grafana RPM
  get_url:
    url: https://dl.grafana.com/oss/release/grafana-10.0.0-1.x86_64.rpm
    dest: /tmp/grafana.rpm

- name: Install Grafana
  yum:
    name: /tmp/grafana.rpm
    state: present
    disable_gpg_check: yes

- name: Start Grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes
