SLACK_CHANNEL_NAME=#jenkins-alert
ENVIRONMENT=prod
CODE_BASE_PATH=.
ACTION_MESSAGE=Vault deployment started
KEEP_APPROVAL_STAGE=true

PLAYBOOK=playbook.yml
INVENTORY=inventory.ini

GIT_REPO=https://github.com/arjun247778/vault-shared-library.git